/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ChaiBia3D(props) {
  const { nodes, materials } = useGLTF("models/chaibia.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.label001.geometry} material={materials.VRayMtl6} />
      <mesh
        geometry={nodes.logo_label001.geometry}
        material={materials.VRayMtl5}
      />
      <mesh geometry={nodes.beer001.geometry} material={materials.VRayMtl4} />
      <mesh
        geometry={nodes.bottle1001.geometry}
        material={materials.VRayMtl3}
      />
    </group>
  );
}

useGLTF.preload("models/chaibia.glb");
